config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :riscos
resources :acaos

get '/historicos/risco/:risco', to: 'historicos#index_risco', as: 'historico_risco'
get '/historicos/acao/:acao', to: 'historicos#index_acao', as: 'historico_acao'
get '/historicos/risco/:risco/versao/:versao', to: 'historicos#show_risco', as: 'show_historico_risco'
get '/historicos/acao/:acao/versao/:versao', to: 'historicos#show_acao', as: 'show_historico_acao'

app/models/acao.rb
class Acao < ActiveRecord::Base	
  	acts_as_versioned
  	unloadable
end

app/controllers/acaos_controller.rb
class AcaosController < ApplicationController
  unloadable
  # before_filter :find_project , :only => [:show, :new, :edit, :update]
  # GET /acoes
  # GET /acoes.json
  def index
    @acoes = Acao.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @acoes }
    end
  end

  # GET /acoes/1
  # GET /acoes/1.json
  def show
    @acao = Acao.find(params[:id])
    @risco = Risco.find(@acao.risco_id)
    @project = Project.find(@risco.project_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @acao }
    end
  end

  # GET /acoes/new
  # GET /acoes/new.json
  def new
  	@risco = Risco.find(params[:risco_id])
    @project = Project.find(@risco.project_id)
    @acao = Acao.new
    @members = Member.where(project_id: @project.id)
    @users = []
    @members.each do |member|
      @users += User.where(id: member.user_id)
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @acao }
    end
  end

  # GET /acoes/1/edit
  def edit
    @acao = Acao.find(params[:id])
    @risco = Risco.find(@acao.risco_id)
    @project = Project.find(@risco.project_id)
    @members = Member.where(project_id: @project.id)
    @users = []
    @members.each do |member|
      @users += User.where(id: member.user_id)
    end
  end

  # POST /acoes
  # POST /acoes.json
  def create
    @acao = Acao.new(params[:acao])

    respond_to do |format|
      if @acao.save
        format.html { redirect_to @acao, notice: 'Acao criada.' }
        format.json { render json: @acao, status: :created, location: @acao }
      else
        format.html { render action: "new" }
        format.json { render json: @acao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /acoes/1
  # PUT /acoes/1.json
  def update
    @acao = Acao.find(params[:id])

    respond_to do |format|
      if @acao.update_attributes(params[:acao])
        format.html { redirect_to acao_url(@acao), notice: 'Acao atualizada.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @acao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acoes/1
  # DELETE /acoes/1.json
  def destroy
    @acao = Acao.find(params[:id])
    @risco = Risco.find(2)
    # @project = Project.find(@risco.project_id)
    @acao.destroy

    respond_to do |format|
      format.html { redirect_to riscos_url(:project_id => @risco.project_id) }
      format.json { head :no_content }
    end
  end

  # protected
  # def find_project
  #   begin
  #     @project = Project.find(params[:project_id])
  #   rescue ActiveRecord::RecordNotFound
  #     render_404
  #     @project = nil
  #   rescue => e
  #     flash.now[:error] = e
  #     @project = nil
  #   end
  # end
end

app/helpers/acaos_helper.rb
module AcoesHelper
end

app/views/acaos/_form.html.erb
<div class='box tabular new_issue'>
<%= form_for(@acao) do |f| %>
  <% if @acao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acao.errors.count, "error") %> prohibited this acao from being saved:</h2>

      <ul>
      <% @acao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label 'ID' %>
    <%= f.number_field :id, :value => @acao.id, :readonly => true %>
  </p>
  <p>
    <%= f.label 'Efetiva' %>
    <%= f.check_box :efetivo, {:checked => false} %>
  </p>
  <p>
    <%= f.label 'Tipo' %>
    <%= f.select(:tipo, options_for_select([['Mitigação', 'Mitigação'],['Transferência','Transferência'],['Eliminação','Eliminação'],['Contigência','Contigência']])) %>
  </p>
  <p>
    <%= f.label "Título" %>
    <%= f.text_field :titulo %>
  </p>
  <p>
    <%= f.label 'Descrição' %>
    <%= f.text_area :descricao, :class => 'wiki-edit', :rows => 10, :cols => 60 %>
  </p>
  <p>
    <%= f.label "Atribuído para" %>
    <%= f.collection_select :atribuido_para, @users, :name, :name, :prompt => 'Selecione um membro' %>
  </p>
  <p>
    <%= f.label "Prazo" %>
    <%= f.text_field :prazo %> <%= calendar_for('acao_prazo') %>
  </p>
  <p>
    <%= f.label "Data de conclusão" %>
    <%= f.text_field :data_de_conclusao %> <%= calendar_for('acao_data_de_conclusao') %>
  </p>
   <p>
    <%= f.label 'Risco' %>
    <%= f.number_field :risco_id, :value => @risco.id, :readonly => true %>
  </p>
  <br/>
  <p>
    <%= f.submit "Salvar"%>
  </p>
 
<% end %>
</div>

app/views/acaos/edit.html.erb
<div class="contextual">
	<%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>
<h1>Editar Ação</h1>

<%= render 'form' %>

app/views/acaos/index.html.erb
<h2>Ações</h2>

<table class="list issues">
  <thead>
      <tr>
        <th>ID</th>
        <th>Tipo</th>
        <th>Título</th>
        <th>Artibuído para</th>
        <th>Prazo</th>
        <th>Data de conclusão</th>
        <th>Risco</th>
        <th></th>
        <th></th>
      </tr>
  </thead>

  <tbody>
  <% @acoes.each do |acao| %>
  <tr class="issue">
    <td><%= link_to '#' + acao.id.to_s, acao %></td>
    <td><%= acao.tipo %></td>
    <td><%= acao.titulo %></td>
    <td><%= acao.atribuido_para %></td>
    <td><%= acao.prazo %></td>
    <td><%= acao.data_de_conclusao %></td>
    <td><%= link_to '#'+ acao.risco_id.to_s, risco_path(:id => acao.risco_id, :project_id => @project.identifier) %></td>

    <td><%= link_to 'Editar', edit_acao_path(acao), :class => 'icon icon-edit' %></td>
    <td><%= link_to 'Excluir', acao_path(acao), method: :delete, data: { confirm: 'Deseja realmente excluir?' }, :class => 'icon icon-del' %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<br />

app/views/acaos/new.html.erb
<div class="contextual">
	<%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>
<h1>Nova Acão</h1>

<%= render 'form' %>

app/views/acaos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="contextual">
  <%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
  <%= link_to 'Editar', edit_acao_path(@acao), :class => 'icon icon-edit' %>
  <%= link_to 'Excluir', acao_path(@acao), method: :delete, data: { confirm: 'Deseja realmente excluir?' }, :class => 'icon icon-del' %>
  <%= link_to 'Histórico', historico_acao_path(:acao => @acao, :project_id => @project.identifier), :class => 'icon icon-history' %>
</div>
<h2> 
  Ação #<%= @acao.id %>
</h2>

<div class='issue tracker-1 status-1 priority-2 priority-default created-by-me details'>
<div class="subject">
<h3>Titulo: <%= @acao.titulo %></h3>
  
</div>
<p>
  
</p>
<p>
  <b>Tipo:</b>
  <%= @acao.tipo %>
</p>

<p>
  <b>Descrição:</b>
  <%= @acao.descricao %>
</p>

<p>
  <b>Atribuído para:</b>
  <%= @acao.atribuido_para %>
</p>

<p>
  <b>Prazo:</b>
  <%= @acao.prazo %>
</p>

<p>
  <b>Data de conclusao:</b>
  <%= @acao.data_de_conclusao %>
</p>

<p>
  <b>Risco:</b>
  <%= link_to '#'+ @acao.risco_id.to_s, risco_path(@risco, :project_id => @project.identifier) %>
</p>