config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :riscos
resources :acaos

get '/historicos/risco/:risco', to: 'historicos#index_risco', as: 'historico_risco'
get '/historicos/acao/:acao', to: 'historicos#index_acao', as: 'historico_acao'
get '/historicos/risco/:risco/versao/:versao', to: 'historicos#show_risco', as: 'show_historico_risco'
get '/historicos/acao/:acao/versao/:versao', to: 'historicos#show_acao', as: 'show_historico_acao'

app/controllers/historicos_controller.rb
class HistoricosController < ApplicationController
before_filter :find_project , :only => [:index_risco, :show_risco, :index_acao, :show_acao]
	def index_risco
		@risco = Risco.find params[:risco]
		@historicos = @risco.versions
	end
	
	def index_acao
		@acao = Acao.find params[:acao]
		@historicos = @acao.versions	
	end

	def show_risco
		@risco = Risco.find params[:risco]
		@versao = @risco.find_version(params[:versao])
	end

	def show_acao
		@acao = Acao.find params[:acao]
		@versao = @acao.find_version(params[:versao])
	end

 protected
  def find_project
    begin
      @project = Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      render_404
      @project = nil
    rescue => e
      flash.now[:error] = e
      @project = nil
    end
  end
end

app/views/historicos/index_acao.html.erb
<div class="contextual">
  <%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>

<h2>Histórico - Ação #<%= @acao.id %> </h2>
<div class="autoscroll" >
<table class="list issues">
  <tr>
    <th>Versão</th>
    <th>Data de Modificação</th>
  </tr>

<% for version in @historicos.reverse %>
  	<tr class="issue">
		<td><%= link_to '#' + version.version.to_s, show_historico_acao_path(:acao => @acao, :versao =>version.version, :project_id => @project.identifier) %></td>
		<td><%=version.updated_at.to_formatted_s(:long) %></td>
	</tr>
<% end %>
</table>
</div>

app/views/historicos/index_risco.html.erb
<div class="contextual">
  <%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>

<h2>Histórico - Risco #<%= @risco.id %> </h2>
<div class="autoscroll" >
<table class="list issues">
  <tr>
    <th>Versão</th>
    <th>Data de Modificação</th>
  </tr>

<% for version in @historicos.reverse %>
  	<tr class="issue">
		<td><%= link_to '#' + version.version.to_s, show_historico_risco_path(:risco => @risco, :versao =>version.version, :project_id => @project.identifier) %></td>
		<td><%=version.updated_at.to_formatted_s(:long) %></td>
	</tr>
<% end %>
</table>
</div>

app/views/historicos/show_acao.html.erb
<div class="contextual">
  <%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>
<h2> 
  Ação #<%= @versao.acao_id %> - Versão <%= @versao.version %> alterada em: <%=@versao.updated_at.to_formatted_s(:long) %>
</h2>

<div class='issue tracker-1 status-1 priority-2 priority-default created-by-me details'>
<div class="subject">
<h3>Titulo: <%= @versao.titulo %></h3>
  
</div>
<p>
  
</p>
<p>
  <b>Tipo:</b>
  <%= @versao.tipo %>
</p>

<p>
  <b>Descrição:</b>
  <%= @versao.descricao %>
</p>

<p>
  <b>Atribuído para:</b>
  <%= @versao.atribuido_para %>
</p>

<p>
  <b>Prazo:</b>
  <%= @versao.prazo %>
</p>

<p>
  <b>Data de conclusao:</b>
  <%= @versao.data_de_conclusao %>
</p>

<p>
  <b>Risco:</b>
  <%= link_to '#'+ @versao.risco_id.to_s, risco_path(:id => @versao.risco_id, :project_id => @project.identifier) %>
</p>

app/views/historicos/show_risco.html.erb
<div class="contextual">
  <%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>
<h2> 
  Risco #<%= @versao.risco_id %> - Versão <%= @versao.version %> alterada em: <%=@versao.updated_at.to_formatted_s(:long) %>
</h2>
<div class='issue tracker-1 status-1 priority-2 priority-default created-by-me details'>
<div class="subject">
  <h3>
    Título: <%= @versao.titulo %>
  </h3>
</div>

<br/>

<table class="attributes">
<tr>
  <th>Origem: </th>
  <td><%= @versao.origem %></td>
</tr>

<tr>
  <th >Descrição: </th>
  <td ><%= @versao.descricao %></td>
</tr>

<tr> 
  <th>Status: </th>
  <td><%= @versao.status %></td>
  <th>Fonte: </th>
  <td><%= @versao.fonte %></td>
</tr>

<tr>
  <th>Categoria: </th>
  <td><%= @versao.categoria %></td>
  <th>Data de identificação: </th>
  <td><%= @versao.data_identificacao %></td>  
</tr>

<tr>
  <th>Adicionado por: </th>
  <td><%= @versao.criado_por %></td>
  <th>Atribuído para: </th>
  <td><%=@versao.dono %></td>
</tr>

<tr>
  <th>Probabilidade: </th>
  <td><%= @versao.probabilidade %></td>
  <th>Impacto: </th>
  <td><%=@versao.impacto %></td>
</tr>

<tr>
  <th>Prioridade: </th>
  <td><%= @versao.prioridade %></td>
  <th>Estratégia: </th>
  <td><%=@versao.estrategia %></td>
</tr>

<tr>
  <th >Gatilho: </th>
  <td ><%= @versao.gatilho %></td>
</tr>
</table>