config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :riscos
resources :acaos

get '/historicos/risco/:risco', to: 'historicos#index_risco', as: 'historico_risco'
get '/historicos/acao/:acao', to: 'historicos#index_acao', as: 'historico_acao'
get '/historicos/risco/:risco/versao/:versao', to: 'historicos#show_risco', as: 'show_historico_risco'
get '/historicos/acao/:acao/versao/:versao', to: 'historicos#show_acao', as: 'show_historico_acao'

app/models/risco.rb
class Risco < ActiveRecord::Base
	acts_as_versioned
  	unloadable
end

app/controllers/riscos_controller.rb
class RiscosController < ApplicationController
  unloadable
  before_filter :find_project , :only => [:index, :show, :new, :edit, :destroy]
  # GET /riscos
  # GET /riscos.json
  def index
    @riscos = Risco.where(project_id: @project.identifier)
    @acoes = []
    @riscos.each do |risco|
        @acoes += Acao.where(risco_id: risco.id)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @riscos }
    end
  end

  # GET /riscos/1
  # GET /riscos/1.json
  def show
    @risco = Risco.find(params[:id])
    @acoes = Acao.where(risco_id: @risco.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @risco }
    end
  end

  # GET /riscos/new
  # GET /riscos/new.json
  def new
    @members = Member.where(project_id: @project.id)
    @users = []
    @members.each do |member|
      @users += User.where(id: member.user_id)
    end
    @adicionadoPor = User.current.name
    @risco = Risco.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @risco }
    end
  end

  # GET /riscos/1/edit
  def edit
    @risco = Risco.find(params[:id])
    @members = Member.where(project_id: @project.id)
    @users = []
    @members.each do |member|
      @users += User.where(id: member.user_id)
    end
    @adicionadoPor = @risco.criado_por
  end

  # POST /riscos
  # POST /riscos.json
  def create
    @risco = Risco.new(params[:risco])

    respond_to do |format|
      if @risco.save
        format.html { redirect_to risco_path(@risco, :project_id => @risco.project_id), notice: 'Risco criado.' }
        format.json { render json: @risco, status: :created, location: @risco }
      else
        format.html { render action: "new" }
        format.json { render json: @risco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /riscos/1
  # PUT /riscos/1.json
  def update
    @risco = Risco.find(params[:id])

    respond_to do |format|
      if @risco.update_attributes(params[:risco])
        format.html { redirect_to risco_path(@risco, :project_id => @risco.project_id), notice: 'Risco atualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @risco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riscos/1
  # DELETE /riscos/1.json
  def destroy
    @risco = Risco.find(params[:id])
    @risco.destroy

    respond_to do |format|
      format.html { redirect_to riscos_url(:project_id => @project.identifier) }
      format.json { head :no_content }
    end
  end

  protected
  def find_project
    begin
      @project = Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      render_404
      @project = nil
    rescue => e
      flash.now[:error] = e
      @project = nil
    end
  end
end

app/helpers/riscos_helper.rb
module RiscosHelper
end

app/views/riscos/_form.html.erb
<div class='box tabular new_issue'>
<%= form_for(@risco) do |f| %>
  <% if @risco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@risco.errors.count, "error") %> prohibited this risco from being saved:</h2>

      <ul>
      <% @risco.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :project_id, :value => @project.identifier %>
  <%= hidden_field_tag 'fonte', @risco.fonte %>
  <%= hidden_field_tag 'categoria', @risco.categoria %>

  <p>
    <%= f.label 'ID' %>
    <%= f.number_field :id, :value => @risco.id, :readonly => true %>
  </p>
  <div class="splitcontentright">
  <p>
    <%= f.label "Esforço" %>
    <%= f.text_field :esforco  %> - Horas
  </p>
  <p>
    <%= f.label "Custo" %>
    <%= f.text_field :custo, :value => (number_with_precision(@risco.custo, :precision => 2) || 0) %>
  </p>
  </div>
  <p>
    <%= f.label 'Título' %><span class="required">*</span>
    <%= f.text_field :titulo, :required => true %>
  </p>
  <p>
    <%= f.label "Status" %>
    <%= f.select(:status, options_for_select([['Aberto', 'Aberto'],['Fechado','Fechado'],['Em Andamento','Em Andamento'],['Suspenso','Suspenso'],['Cancelado','Cancelado'], ['Rejeitado','Rejeitado'], ['Resolvido','Resolvido']])) %>
  </p>
  <p>
    <%= f.label "Origem" %>
    <%= f.select(:origem, options_for_select( [ ['Projeto', 'Projeto'], ['Organizacional', 'Organizacional'] ] )) %>
  </p>
  <p>
    <%= f.label "Descrição"%><span class="required">* </span>
    <%= f.text_area :descricao, :required => true, :class => 'wiki-edit', :rows => 10, :cols => 60  %>
  </p>
  <div class="splitcontentleft">
  <p>
    <%= f.label "Fonte" %>
    <%= f.select(:fonte, options_for_select([['Selecione uma fonte',''],['Ambiente organizacional','Ambiente organizacional'],['Usuário','Usuário'],['Requisitos','Requisitos'],['Complexidade do projeto','Complexidade do projeto'],['Planejamento e controle','Planejamento e controle'],['Time','Time']])) %>
  </p>
  <p>
    <%= f.label "Categoria" %>
    <%= f.select(:categoria , options_for_select([['Selecione uma categoria','']])) %>
  </p> 
  <p>
    <%= f.label "Probabilidade" %>    
    <%= f.select(:probabilidade, options_for_select([['Muito Baixa','Muito Baixa'],['Baixa','Baixa'],['Média','Média'],['Alta','Alta'],['Muito Alta','Muito Alta']]))  %>
  </p>
  <p>
    <%= f.label 'Impacto'%>
    <%= f.select(:impacto, options_for_select([['Muito Baixo','Muito Baixo'],['Baixo','Baixo'],['Médio','Médio'],['Alto','Alto'],['Muito Alta','Muito Alto']]))  %>
  </p>
  <p>
    <%= f.label 'Prioridade' %>
    <%= f.text_field :prioridade, :readonly => true %>
  </p>
  </div>
  <div class="splitcontentright">
  <p>
    <%= f.label "Data de identificação" %>
    <%= f.text_field :data_identificacao %> <%= calendar_for('risco_data_identificacao') %>
  </p>
  <p>
    <%= f.label 'Adiconado por' %>
    <%= f.text_field :criado_por, :value => @adicionadoPor, :readonly => true %>
  </p>
  <p>
    <%= f.label 'Atribuído para' %>
    <%= f.collection_select :dono, @users, :name, :name, :prompt => 'Selecione um membro' %>
  </p>
  <p>
    <%= f.label 'Estratégia' %>
    <%= f.select(:estrategia, options_for_select([['Eliminar','Eliminar'],['Transferir','Transferir'],['Mitigar','Mitigar'],['Aceitar','Aceitar']])) %>
  </p>
  </div>
  <p>
    <%= f.label "Gatilho" %>
    <%= f.text_area :gatilho, :class => 'wiki-edit', :rows => 10, :cols => 60 %>
  </p>
  <br/>
  <p>
    <%= f.submit "Salvar"%>
  </p>
<% end %>
<script type="text/javascript">
  $(document).ready(function() {
    var fonte = $('#fonte').val();
    var categoria = $('#categoria').val();
    console.log (fonte);
    $('#risco_fonte').val(fonte);
    carregarCategorias(fonte);
    $('#risco_categoria').val(categoria);
    $('#risco_fonte').change(function() {
      var fonteSelected = $('#risco_fonte').val();
      carregarCategorias(fonteSelected);
    });

    $('#risco_probabilidade').change(function() {
      prioridade = calcularPrioridade($('#risco_probabilidade').val(), $('#risco_impacto').val());
      $('#risco_prioridade').val(prioridade);
    });

    $('#risco_impacto').change(function() {
      prioridade = calcularPrioridade($('#risco_probabilidade').val(), $('#risco_impacto').val());
      $('#risco_prioridade').val(prioridade);
    });

    function carregarCategorias(fonteSelected){
      var fontes = associarCategoriasAFontes();
      if(fonteSelected == ""){
        $("#risco_categoria").empty();
        var html = "<option value=''> Selecione uma categoria</option>";
        $("#risco_categoria").append(html);
      }else{
        var categorias = fontes[fonteSelected];
        $("#risco_categoria").empty();
        for (var i = 0; i < categorias.length ; i++) {
          var html = '<option value="' +  categorias[i] +'">' + categorias[i] + '</option>';
          $("#risco_categoria").append(html);
        };
      }
    }

    function calcularPrioridade(probabilidade, impacto){
      var arrayProbabilidade = criarArrayProbabilidade();
      var arrayImpacto = criarArrayImpacto();
      var matrizPrioridade = criarMatrizPrioridade();

      return matrizPrioridade[arrayProbabilidade[probabilidade]][arrayImpacto[impacto]];
    }

    function associarCategoriasAFontes(){
      var fontes = new Array();

      fontes['Ambiente organizacional'] = ['Política organizacional','Apoio organizacional','Ambiente'];
      fontes['Usuario'] = ['Envolvimento do usuário','Usuário'];
      fontes['Requisitos'] = ['Requisitos funcionais', 'Requisitos não funcionais', 'Requisitos'];
      fontes['Complexidade do projeto'] = ['Tecnologia utilizada', 'Processos'];
      fontes['Planejamento e controle'] = ['Cronograma', 'Orçamento', 'Marcos', 'Estimativa de duração', 'Gestores'];
      fontes['Time'] = ['Insuficiência de equipe', 'Conhecimento', 'Cooperação', 'Motivação', 'Comunicação'];

      return fontes;
    }

    function criarArrayProbabilidade(){
      var probabilidade = new Array();
      probabilidade['Muito Baixa'] = 0;
      probabilidade['Baixa'] = 1;
      probabilidade['Média'] = 2;
      probabilidade['Alta'] = 3;
      probabilidade['Muito Alta'] = 4;
      return probabilidade;
    }

    function criarArrayImpacto(){
      var impacto = new Array();
      impacto['Muito Baixo'] = 0;
      impacto['Baixo'] = 1;
      impacto['Médio'] = 2;
      impacto['Alto'] = 3;
      impacto['Muito Alto'] = 4;
      return impacto;
    }
    function criarMatrizPrioridade(){
      var matrizPrioridade = createMatriz(5,5);
      matrizPrioridade[0][0] = 'Muito Baixa';
      matrizPrioridade[0][1] = 'Muito Baixa';
      matrizPrioridade[0][2] = 'Baixa';
      matrizPrioridade[0][3] = 'Média';
      matrizPrioridade[0][4] = 'Média';
      matrizPrioridade[1][0] = 'Muito Baixa';
      matrizPrioridade[1][1] = 'Baixa';
      matrizPrioridade[1][2] = 'Média';
      matrizPrioridade[1][3] = 'Média';
      matrizPrioridade[1][4] = 'Alta';
      matrizPrioridade[2][0] = 'Muito Baixa';
      matrizPrioridade[2][1] = 'Baixa';
      matrizPrioridade[2][2] = 'Média';
      matrizPrioridade[2][3] = 'Alta';
      matrizPrioridade[2][4] = 'Alta';
      matrizPrioridade[3][0] = 'Baixa';
      matrizPrioridade[3][1] = 'Média';
      matrizPrioridade[3][2] = 'Alta';
      matrizPrioridade[3][3] = 'Alta';
      matrizPrioridade[3][4] = 'Muito Alta';
      matrizPrioridade[4][0] = 'Baixa';
      matrizPrioridade[4][1] = 'Alta';
      matrizPrioridade[4][2] = 'Muito Alta';
      matrizPrioridade[4][3] = 'Muito Alta';
      matrizPrioridade[4][4] = 'Muito Alta';
      return matrizPrioridade;
    }
    function createMatriz(x,y){
      mt = new Array();
      for(i=0; i<x; i++){
        mt[i] = new Array();
        for(j=0; j<y; j++){
          mt[i][j] = -1;
        }
      }
    return mt;
    }

  });
</script>
</div>

app/views/riscos/edit.html.erb
<div class="contextual">
	<%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>
<h1>Editar Risco</h1>

<%= render 'form' %>

app/views/riscos/index.html.erb
<div class="contextual">
    <%= link_to 'Novo Risco', new_risco_path(:project_id => @project.identifier), :class => 'icon icon-add'%>
</div>
<h1>Riscos</h1>
<div class="autoscroll" >
<table class="list issues">
  <tr>
    <th>ID</th>
    <th>Título</th>
    <th>Status</th>
    <th>Prioridade</th>
    <th>Data de identificação</th>
    <th></th>
    <th></th>
  </tr>

<% @riscos.each do |risco| %>
  <tr class="issue">
    <td><%= link_to '#'+ risco.id.to_s, risco_path(risco, :project_id => @project.identifier) %> </td>
    <td><%= risco.titulo %></td>
    <td><%= risco.status %></td>
    <td><%= risco.prioridade %></td>
    <td><%= risco.data_identificacao %></td>
    <td><%= link_to 'Editar', edit_risco_path(risco, :project_id => @project.identifier), :class => 'icon icon-edit' %></td>
    <td><%= link_to 'Excluir', risco_path(risco, :project_id => @project.identifier), method: :delete, data: { confirm: 'Deseja realmente excluir?' }, :class => 'icon icon-del' %></td>
  </tr>
<% end %>
</table>
</div>
<br />
<hr/>
<%= render :template => 'acaos/index' %>

app/views/riscos/new.html.erb
<div class="contextual">
	<%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
</div>
<h1>Novo Risco</h1>

<%= render 'form' %>

app/views/riscos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="contextual">
  <%= link_to_function 'Voltar', "history.back()", :class => 'icon icon-reload' %>
  <%= link_to 'Editar', edit_risco_path(@risco, :project_id => @project.identifier), :class => 'icon icon-edit' %>
  <td><%= link_to 'Excluir', risco_path(@risco, :project_id => @project.identifier), method: :delete, data: { confirm: 'Deseja realmente excluir?' }, :class => 'icon icon-del' %></td>
  <%= link_to 'Histórico', historico_risco_path(:risco => @risco, :project_id => @project.identifier), :class => 'icon icon-history' %>
</div>
<h2> 
  Risco #<%= @risco.id %>
</h2>
<div class='issue tracker-1 status-1 priority-2 priority-default created-by-me details'>
<div class="subject">
  <h3>
    Título: <%= @risco.titulo %>
  </h3>
</div>

<br/>

<table class="attributes">
<tr>
  <th>Origem: </th>
  <td><%= @risco.origem %></td>
</tr>

<tr>
  <th >Descrição: </th>
  <td ><%= @risco.descricao %></td>
</tr>

<tr> 
  <th>Status: </th>
  <td><%= @risco.status %></td>
  <th>Fonte: </th>
  <td><%= @risco.fonte %></td>
</tr>

<tr>
  <th>Categoria: </th>
  <td><%= @risco.categoria %></td>
  <th>Data de identificação: </th>
  <td><%=@risco.data_identificacao %></td>  
</tr>

<tr>
  <th>Adicionado por: </th>
  <td><%= @risco.criado_por %></td>
  <th>Atribuído para: </th>
  <td><%=@risco.dono %></td>
</tr>

<tr>
  <th>Probabilidade: </th>
  <td><%= @risco.probabilidade %></td>
  <th>Impacto: </th>
  <td><%=@risco.impacto %></td>
</tr>

<tr>
  <th>Prioridade: </th>
  <td><%= @risco.prioridade %></td>
  <th>Estratégia: </th>
  <td><%=@risco.estrategia %></td>
</tr>

<tr>
  <th >Gatilho: </th>
  <td ><%= @risco.gatilho %></td>
</tr>

</table>


<hr/>
<%= render :template => 'acaos/index' %>
<%= link_to 'Nova ação', new_acao_path(:risco_id => @risco.id), :class => 'icon icon-add' %>